### ISSUE TITLE
Getting Travis CI build error while making pull request

### ISSUE THREAD

**Issue by gautamkvashisht** [freeCodeCamp/guides#1388]
When I make a pull request, I get Travis CI build error and build fails. How to solve this issue ?
This is the pull request I have made :-
https://github.com/freeCodeCamp/guides/pull/1413

**Comment by johnkennedy9147** [comment]
@gautamkvashisht as you spotted the first commit build failed due to file naming, you fixed this for your second commit but it also failed as the articles are missing the frontmatter.  I see you submitted a new PR #1441 - you can make the amendments and then update that PR.

The frontmatter provides the article title in the sidenav, example frontmatter from Go article:
```
---
title: Go
---
```

add the appropriate 3 lines right at the start of each file and they should be fine.

**Comment by gautamkvashisht** [comment]
@johnkennedy9147 Thanks for your help ! :+1:

**Comment by texas2010** [comment]
@johnkennedy9147 thank you for help him.
