### ISSUE TITLE
Fix placeholder text in angle brackets 

### ISSUE THREAD

**Issue by williamsb** [freeCodeCamp/guides#246]
I recently submitted a pull request fixing issue #239 where placeholder text in angle brackets were being rendered as html tags, for example < url of repository> being rendered as < urlofrepository >< /urlofrepository>.

However, upon browsing through the rest of the Git section I have found at least 15 instances of the same issue in Git Branch, 3 in Git, and 1 in Git Stash.

I am wondering if perhaps it would be better to use these [ ] brackets instead, it would eliminate future errors and be consistent with syntax in the FCC guides.

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#adding-your-branch

**Comment by HKuz** [comment]
Hi @williamsb thanks for fixing and finding these - I agree with you that we should change convention instead of using escape characters (it'll be cleaner and easier to remember 😄). How about instead of any brackets, we just put the text in question in all caps with hyphens (kind of like the PR instructions in the Readme for this repository):

`git clone URL-OF-REPOSITORY`

Speaking of the Readme, I can update that to conform the commands so they all have the same formatting 👍

**Comment by Bouncey** [comment]
Sounds good to me 👍 

@williamsb can you take care of the other articles in your existing PR?
