### ISSUE TITLE
Yarn Install Fails

### ISSUE THREAD

**Issue by m-henderson** [freeCodeCamp/guides#348]
I have checked this over and over again, I cant see where this is on my end. Could you all have a look at it and let me know what you think ? running yarn install on a fresh clone of guides fails. 
![image](https://user-images.githubusercontent.com/16070192/30779172-a02adc0c-a0ae-11e7-9f71-995a2fbfd404.png)
![image](https://user-images.githubusercontent.com/16070192/30779176-b0c6f456-a0ae-11e7-87c0-ba3abb57a398.png)

**Comment by Bouncey** [comment]
@m-henderson do you get any errors? Which version of yarn?

**Comment by m-henderson** [comment]
yarn version 1.0.2 , instead of running yarn install, I did a npm install and then yarn run dev. The site is running find on local machine. idk why i am getting that error now when running yarn install

**Comment by systimotic** [comment]
Hi Michael!

Our current installation includes the `sharp` image processing module, which is a native module that's compiled using `node-gyp`. From the error, it seems like you don't have it set up, and it's not included in our installation instructions. I also had issues with it, because it works differently with yarn and npm. This is not an issue on MacOS because python is preinstalled.

@zk433 had the exact same issue a couple of days ago.

We could include `node-gyp` installation instructions for Windows, but I think there's an easier solution. I believe we have included `sharp` because it was in the boilerplate, but we're not actually using it. Things should work fine if we remove it. Doing this was already on my never-ending todo-list, but now that others are having issues with this, I'll try to make sure I do it sooner.

**Comment by divayprakash** [comment]
@systimotic Working on it!

**Comment by divayprakash** [comment]
@systimotic So I need a little bit of help here. I removed the `gatsby-plugin-sharp` dependency from `package.json` and also from `gatsby-config.js`. The `yarn build` did not hit any errors then and completed successfully on a fresh clone of the repo on my Windows 10 machine. I would also like to clarify that I did not have the `sharp` module installed/pre-configured.

Now the issue I have is that besides the changes in `package.json` and `gatsby-config.js` I am also getting a lot of changes to the `yarn.lock` file. Should I commit these changes or disregard them and commit the former 2 files only?

**Comment by Bouncey** [comment]
@divayprakash please ensure you have ran `yarn remove gatsby-plugin-sharp` to remove it the the `package.json`. And yes please commit the `yarn.lock` file 👍

**Comment by m-henderson** [comment]
@Bouncey @divayprakash @systimotic good work! I figured this was on my end, but I wasn't sure. better safe than sorry (:

**Comment by systimotic** [comment]
@m-henderson This should now be fixed thanks to @divayprakash. Can you check it out?

**Comment by m-henderson** [comment]
@systimotic running like a well oiled machine. 
![2017-09-25](https://user-images.githubusercontent.com/16070192/30810344-7088c3d4-a1ca-11e7-91bf-799bcb14be90.png)
