### ISSUE TITLE
Comments in HTML not displaying properly

### ISSUE THREAD

**Issue by dwaq** [freeCodeCamp/guides#453]
See this page: https://guide.freecodecamp.org/html/comments-in-html

It should appear as:

		<h1>FreeCodeCamp web</h1>

		

		<p>FreeCodeCamp is an open-source project that needs your help</p>

Note, in order to even make this issue appear correctly, I had to indent the HTML tags and leave a blank space between the lines. I did not use the back ticks feature.

See this image:
![image](https://user-images.githubusercontent.com/1299430/30859589-5adbbcbc-a292-11e7-8f2f-b8c88cfeff16.png)

**Comment by danedavid** [comment]
I dont understand the issue. You want the comment to be displayed on the page ?

**Comment by dwaq** [comment]
I don't understand why there's an example on the page if you can't see it.

**Comment by systimotic** [comment]
Thanks for reporting this @dwaq!

The source for this article is [here](https://github.com/freeCodeCamp/guides/blob/18b9668e84be5715267eaf7efecfe9d1454ea5ec/src/pages/html/comments-in-html/index.md).
We're currently having an issue where HTML inside code blocks is being executed, unless the code block is marked as an HTML code block.
To fix this issue here, the first ` ``` ` in the file linked above needs to be changed to ` ```html `
