### ISSUE TITLE
announcement : prevent spam contributions to the repo for hacktoberfest

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/guides#4639]
Hello,

It's been evident that many contributions to the repo are not made in the good spirit of Hacktoberfest, lots of which are either spammy or are extremely low-effort like adding and removing punctuations.

This is unfair to all of the genuine efforts that the super awesome community has done.
Luckily we have a way to be fair to the contributors.

We would be marking such contributions as `invalid`. Hacktoberfest will exclude such pull requests from their evaluation. 

If there is an ambiguity in any pull request, please reach out to us in the Contributors chat. We will be glad to assist.

_Note: If you find that your contribution was marked invalid in error, you can report the same stating the reason, and we will get back to you in rectifying._

Happy Fixing!

@freeCodeCamp/moderators :
**Please mark any pull requests that are low-effort or spam by tagging them with an `invalid` label including those that are already closed.**

/cc @QuincyLarson @BerkeleyTrue

**Comment by raisedadead** [comment]
Quick links:

##### [Check Open Unmerged Issues after 1st October](https://github.com/freeCodeCamp/guides/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aunmerged%20is%3Aopen%20created%3A%3E2017-10-01%20)
##### [Check Closed Unmerged Issues after 1st October](https://github.com/freeCodeCamp/guides/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aunmerged%20is%3Aclosed%20created%3A%3E2017-10-01%20)

**Comment by texas2010** [comment]
Sure. I can do that.

**Comment by texas2010** [comment]
I meant to say I can do that in some PR. but not today.

**Comment by HKuz** [comment]
Thanks for formalizing this in an issue, @raisedadead - agree completely that spammy/low-effort PRs just for the t-shirt aren't fair to those who make genuine contributions. I'd add that we should mark all PRs against the old `guide-articles` repository as `invalid` as well. I know some of these were honest mistakes, but @texas2010 and I have been re-directing them to this repo, and asking them to re-submit their PR here.

**Comment by BerkeleyTrue** [comment]
@

**Comment by BerkeleyTrue** [comment]
@raisedadead Sounds good

**Comment by Ethan-Arrowood** [comment]
Feel free to ping me on any PR if you need a secondary reviewer

**Comment by IsaacAbrahamson** [comment]
I think this might be a good thing to state in rules for contributing.

**Comment by Ethan-Arrowood** [comment]
Hey guys we need to get all contributors on the same page here. I closed someones' [PR](https://github.com/freeCodeCamp/guides/pull/4838) today for lack of effort and then they commented asking why because this: https://github.com/freeCodeCamp/guides/pull/1614 got merged. I know things are changing rapidly, but we should fast track a proper CONTRIBUTING and README guidelines. I'm going to work on some sort of precommit script tonight with an idea I've been thinking about to dramatically lower the amount people are contributing.

**Comment by systimotic** [comment]
@Ethan-Arrowood 👍 👍 Do keep in mind that a pre-commit script does not run when commits are created using the GitHub web interface (almost all PR's are created there because we recommend it in the README and Medium articles). If you want it to run for every Pull Request, we might need to add it to the test suite (so it runs in the CI) or create a bot like @camperbot that closes invalid PR's automatically with an explanation.

Additionally, we should make what we do and don't accept clear in advance. Adding it to the README would be a good first step, but stuff in there is often missed. I think adding a Pull Request template that has some short comments explaining what we want could help a lot.

**Comment by Ethan-Arrowood** [comment]
👍 
>I think adding a Pull Request template that has some short comments explaining what we want could help a lot.

👍 
> create a bot like @camperbot that closes invalid PR's automatically with an explanation.

**Comment by raisedadead** [comment]
Can someone add this to the PR template? I am expanding the camper-gh-bot's functionality for some automation, but that might take a while.

**Comment by HKuz** [comment]
@raisedadead and others - looks like this repo doesn't have the `.github` folder - I'll create on and take a first cut at the PR template.

**Comment by QuincyLarson** [comment]
I believe this is now resolved thanks to @HKuz's PR: https://github.com/freeCodeCamp/guides/pull/5171

If this is still an issue, please re-open the PR.
