### ISSUE TITLE
Fix navbar height

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#68]
The navbar should be 40px tall, which is what we're planning to use throughout freecodecamp.org. The logo and search box should be vertically centered within the nav bar.

**Comment by invinciblycool** [comment]
I would like to take this up.

**Comment by Bouncey** [comment]
@invinciblycool Great! Thanks for contributing 👍 

If you encounter any difficulty, comment here or try [the Contributors Chat on gitter.im](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by invinciblycool** [comment]
I have opened a PR regarding the issue.

**Comment by invinciblycool** [comment]
I have linted the code, should I open a new PR regarding the same.

**Comment by Bouncey** [comment]
@invinciblycool, there was no need to close that PR, you could have fixed the linting issues and amended the commit. The steps required in git are as follows:

```sh
git checkout fix/navbarheightto40px
# fix the linting issues
git commit -a --amend
# Ctrl + O, Ctrl + X
git push origin fix/navbarheightto40px -f
```

**Comment by invinciblycool** [comment]
Thanks, will keep in mind from now onwards.

**Comment by systimotic** [comment]
I'm not sure whether this is a good idea. While I'm all for consistency, when you need to fit an input in there, 40px is really tight.

![firefox_2017-08-23_00-11-57](https://user-images.githubusercontent.com/7262039/29590103-7a2ea79c-8798-11e7-98e8-c588edeea65c.png)
This is what it would look like if we would just change the height without changing the input. In the context of the full page, it looks even more crammed than in the screenshot.
  
![firefox_2017-08-23_00-13-24](https://user-images.githubusercontent.com/7262039/29590114-8058e1e6-8798-11e7-8fa2-e51fa1756aa3.png)
For reference, this is what it would look like with a 50px height.
  
![firefox_2017-08-23_00-13-04](https://user-images.githubusercontent.com/7262039/29590113-80570e3e-8798-11e7-9d5f-218894f7aafa.png)
This is what happens when you make the input smaller as well as going to 40px. Now the input is tiny, but the spacing around it is a bit better. I think this doesn't make it better at all.
  
![firefox_2017-08-23_00-17-14](https://user-images.githubusercontent.com/7262039/29590112-8026323c-8798-11e7-983a-f9d615225f00.png)
This is 40px, but with the input using the full height. I think this could be a good compromise. The downside is that it may look a bit less like an input.

@QuincyLarson @Bouncey What do you think?

**Comment by QuincyLarson** [comment]
@systimotic Thanks for investigating this. I think the third one (40px with a bit of spacing above and below) is best, for the reasons you mentioned (the fill-height one doesn't look sufficiently like an input box).

A lot of websites have 40px navbars with search bars in them, so I think this size will work. For example, Facebook is 42 pixels:

![_245__facebook](https://user-images.githubusercontent.com/985197/29594146-904bb3b8-8774-11e7-9ea8-619121d28999.png)

**Comment by marijnpool** [comment]
It might be better to declare the height per viewport.

**Comment by QuincyLarson** [comment]
It looks like the navbar is now 36 pixels. Closing this.
