### ISSUE TITLE
Hacktoberfest Information!

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/guides#696]
Contributors,

If you're curious about the "Hacktoberfest" labels and want to get involved, here's a link to the [official Hacktoberfest site](https://hacktoberfest.digitalocean.com/). It has all the rules and a [sign-up link](https://hacktoberfest.digitalocean.com/sign_up/register). The general idea is you sign up, make 4 pull requests on open source projects between October 1-31, and you get stickers and a free t-shirt! Any PRs (fixing typos, writing articles, making platform changes, etc.) on this repository all count 😉 😉 

🎃 Happy coding! 🎃 

PS - With all the activity since the Guide announcement, there's been a lag between when a PR is opened and when it's reviewed. As long as your PR is *opened* between the dates above, it counts.

**Comment by louisheath** [comment]
Hi all, I'm very new to PRs and Hacktoberfest.

I submitted two PRs to the guide, I can spot them on my profile and also on the repo, but when I hit 'Pull Requests' in the nav bar only one of them is visible. Is this just a bug or am I doing something wrong? Thanks!

![prconfusion](https://user-images.githubusercontent.com/28117240/31855945-aa28e464-b6ad-11e7-8491-fd28624f0dec.png)

**Comment by HKuz** [comment]
Hi @louisheath - when I sort PRs by `is:open is:pr author:louisheath` I see two open PRs ( #2784 and #2778), so looks like they are okay on our end! Sometimes GitHub can have a lag, and you just need to refresh it, also, with all the activity (PRs are pouring in), it may just be a little slow to show everything. Thanks for contributing! 🎉

**Comment by tanushree57** [comment]
Hi

I'm not sure how The Travis CI build works but my files failed the checks (it says "The command "node bin/createNavData" exited with 1. Done. Your build exited with 1.") and I'm not sure why or what to do to fix any errors on my end. Also they do show up as my contributions so is that enough or do they have to pass for them to be counted? Can you help me out here?

Thanks.

**Comment by HKuz** [comment]
Hi @tanushree57 - the build has to pass for us to merge a PR (otherwise, we break the site 😢 ). I'm not sure what that error is referring to exactly, but here are the two ways I know of that break the build:

1. You created a new folder or subfolder for your article, but didn't include an `index.md` file - every folder in `src/pages` needs an `index.md` file in it. This has happened when someone creates both a new folder, then a subfolder, writes an article in the subfolder but forgets to put a stub `index.md` file in the new folder
2. Your article doesn't have a title field at the top - every article needs this as the first 3 lines of the `index.md` file:

```
---
title: Title of the article that shows up in the site's menu
---
```

If you want to tell me which PRs you're having issues with, I can take a look and see if I can figure out the error on my end 👍 😄  Thanks for contributing! 🎉

**Comment by dynamicdebian** [comment]
I want to solve this issue

**Comment by tanushree57** [comment]
Hi @HKuz 
Firstly, **thank you** for helping out. Secondly, I had already taken care of the 1st point that you mentioned about creating an index.md file so my folders already had those. So I went onto the next point that you mentioned about there being a title.

Turns out I didn't have a title on any of my pages so I'm guessing that's why the builds failed. I've added them according to the format you specified. But I went on to read somewhere that if you don't explicitly mention a title any H1, H2 or H3 that you start off with is taken as the title by default.
So if that's the case then why did the build fail? Or is it that for this particular test the rule doesn't apply?

Also since I'm a novice at directly editing code here (usually I do it through an IDE that is directly integrated with GitHub) I don't know how to go about checking the latest version of a particular file that I've written. So if I give you the number that is associated with the files when I created it, would that suffice for you to check the issue? It's #2963 now I'm not sure if there's an updated version of it where I've added a title.

@dynamicdebian I think the issue was with the title itself but **thank you** for offering to help. You can take a look at the PR too if you want. I've mentioned the file number above.

**Thanks for all the help guys. It's much appreciated!** :)

**Comment by HKuz** [comment]
@tanushree57 - I just looked at your PR, yes, you need to add the title field at the top of both new files you created - neither of the files I'm looking at in the PR have it. I'm not sure what you read about the H1/2/3 is referring to (perhaps just a site in general for what's displayed as the title for a browser tab?), but the way the fCC Guide site builds, it needs that field at the top of the `index.md` page to know what to put in the menu. If it's not there, the site breaks.

To add new lines in your PR, you should be able to click over the the "Files Changed" section (one of the tabs just under the title of your PR and the big green "Open" label), and edit the files using the pencil icon. Then commit the change so it saves and we see it. If you're still having trouble updating the files, post a comment in the PR and mention me, I can add them for you. 👍

**Comment by meetdshah007** [comment]
I am having issue like this with Travis

> /home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:77
>     throw e;
>     ^
> Error: Error: ENOENT: no such file or directory, open 'src/pages/javascript/singleton-in-javscript/index.md'


> The command "node bin/createNavData" exited with 1.
> Done. Your build exited with 1.

I am trying to create content on new folder. How do i Fix this?
Can someone help fixing this??

**Comment by tanushree57** [comment]
Hi @HKuz 
I'll add them right away. Thank you so much for the help! :) I'll keep this in mind for any future PRs I make.

Also, is there a way to see the latest copy of the file after multiple changes have been made?

**Comment by HKuz** [comment]
@meetdshah007 - you need the `title` field mentioned in my comment [above](https://github.com/freeCodeCamp/guides/issues/696#issuecomment-338973024) to fix your file. 👍

**Comment by HKuz** [comment]
Thanks everyone for participating in Hacktoberfest 🎃! Now that it's officially over, I'm closing this issue.

**Comment by tanushree57** [comment]
@HKuz Thanks alot! This was fun! :)
