### ISSUE TITLE
Arranging articles in order to follow instead of alphabetical order.

### ISSUE THREAD

**Issue by invinciblycool** [freeCodeCamp/guides#697]
Currently the articles on each topic are listed in alphabetical order.
Considering a beginner visiting the guide, it becomes very tiresome to learn a topic from the very beginning because of the difficulty faced in navigating through articles.

Instead if the articles are in a sequence to follow, it would be much better.
Consider the case of python, an article on while loops lies way below the hierarchy.
![articles](https://user-images.githubusercontent.com/24691797/31177477-c999f00e-a933-11e7-90c8-b4e41d72ec4c.png)

**Comment by systimotic** [comment]
@invinciblycool Good point!

Whether we want to stick with this ordering depends on what the goal of the Guide is. As I understood it, the Guide is meant as reference material, not as a guided walk-through on how to learn a subject (that's what the main curriculum is for).

For reference material, I think alphabetical ordering makes sense. That said, we could make this easier by grouping things better. Those string methods could be grouped into a directory, and so could all the loops.

**Comment by invinciblycool** [comment]
Yeah, I hope we will arrive at a conclusion which improves the navigation inside the guide.

**Comment by erictleung** [comment]
@invinciblycool @systimotic I agree on the point to reflect on the purpose of the Guide. I agree that for now, it is more of a reference base rather than a sequential, linear guide to all things. I imagine the guides being non-linear like Wikipedia. In all, I think the Guide should be a complement to learning from another more linear tutorials and learning material.

**Comment by invinciblycool** [comment]
@erictleung I agree with considering Guide as a reference over a sequential guide to things.
But still as @systimotic said, we could still group articles.

**Comment by systimotic** [comment]
I'm glad we agree on this! I think we've come to a conclusion on the original subject of the issue, alphabetical ordering issue is the right choice. Because of that, I'm closing this issue.

Grouping articles is an ongoing process. Feel free to submit PR's or create issues about things that need to be grouped.

Happy coding!
