### ISSUE TITLE
Two ES6 folders in 'src/pages/javascript'

### ISSUE THREAD

**Issue by LulaV14** [freeCodeCamp/guides#7834]
There are two ES6 folders inside 'src/pages/javascript/'. One called [ES6](https://github.com/freeCodeCamp/guides/tree/master/src/pages/javascript/ES6) and the other [es6](https://github.com/freeCodeCamp/guides/tree/master/src/pages/javascript/es6). 
The one in uppercase is giving me trouble in git while doing a rebase to master.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by meckanism** [comment]
I'm having this problem as well.
I'm on a fresh clone of my fork, at `master` and I have a modified file at `src/pages/javascript/ES6/index.md`.

As LulaV14 suggests, this seems to be related to the `src/pages/javascript` having two folders with the same name. 

On github we can see the duplicated folders but on my osx and windows machines i cannot. Probably because both filesystems are case insensitive but case preserving.

A possible fix would be to use `git mv` to rename one of the directories.

In the future it would be wise to enforce lowercase in all directory names to prevent this from happening.

**Comment by johnkennedy9147** [comment]
issue resolved by PR #7843. thanks for your contribution
