### ISSUE TITLE
Default image for og:image meta property

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#7895]
Currently the meta properties of guide articles will render the first image in an article as the og:image and twitter image:

![sharing_debugger_-_facebook_for_developers](https://user-images.githubusercontent.com/985197/33284635-5b3da3c8-d375-11e7-8186-068515ccc1a4.png)

But if there is no image in an article, it leaves the og:image property blank, and renders this:

![sharing_debugger_-_facebook_for_developers](https://user-images.githubusercontent.com/985197/33284684-8153b8e0-d375-11e7-8d73-0a695cb41a73.png)

We want to have a deafult image that gets assigned to og:image if there is no image in an article. We're thinking this image from freeCodeCamp's instagram: https://www.instagram.com/p/Ba9TGe4FNi8/?taken-by=freecodecamp

**Comment by spezzino** [comment]
This was fixed on #5225

**Comment by systimotic** [comment]
As @spezzino mentioned, a default image was added in that PR. It's the image at this URL: https://s3.amazonaws.com/freecodecamp/freecodecamp-square-logo-large.jpg

The reason this image isn't showing up in a card is because it returns a 403 on all requests, even with `freecodecamp.org` as origin. I'm not sure why this is happening.

It should be updated to a working image here:
https://github.com/freeCodeCamp/guides/blob/89861a767b1c51e9deab3d9fd2193646ce57a472/src/templates/Article.jsx#L52-L53

**Comment by QuincyLarson** [comment]
@systimotic Awesome! I've updated the asset on S3 and now it's working. Great job, @spezzino! Thanks everyone!
