### ISSUE TITLE
HTML not correctly visible for HTML->Elements->Li Tag

### ISSUE THREAD

**Issue by adiparab14** [freeCodeCamp/guides#7926]
HTML not correctly visible for HTML->Elements->Li Tag
![image](https://user-images.githubusercontent.com/1599508/33712040-4d299e76-db46-11e7-88b6-1069ecf0ec1d.png)
Screenshot is for one sitation. There are multiple situations in the article.
---

> ✅️ By submitting this issue, I have verified the following

- [X] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by systimotic** [comment]
Good catch @adiparab14!

This is related to https://github.com/freeCodeCamp/guides/issues/587. In summary, HTML in code blocks is rendered instead of displayed as code if the language is not specified.

For now, this could be fixed here by specifying the language on the broken code blocks (changing the opening "``\`" to "```html"). Do you want to submit a PR for this @adiparab14?

**Comment by adiparab14** [comment]
@systimotic Submitted a PR
