### ISSUE TITLE
Broken breadcrumbs in search results

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/guides#8028]
#751 added the path of the articles showing up in the search results. However, the breadcrumb with the path doesn't show up right. There's this weird `Https: >  > Guide.freecodecamp.org >` prefix now in all the paths on the search results...

<img width="1280" alt="screen shot 2018-01-29 at 3 33 45 pm" src="https://user-images.githubusercontent.com/16361470/35515690-1e339944-050a-11e8-85b3-285e9eb68726.png">
<img width="1280" alt="screen shot 2018-01-29 at 3 34 29 pm" src="https://user-images.githubusercontent.com/16361470/35515691-1e54a92c-050a-11e8-9dbc-0b212e01d569.png">
<img width="1280" alt="screen shot 2018-01-29 at 3 34 34 pm" src="https://user-images.githubusercontent.com/16361470/35515692-1e73de1e-050a-11e8-95ef-31f65fad99d5.png">

**Comment by dhanushuUzumaki** [comment]
Found the issue. The breadcrumb component is just doing its job as usual but while it's making the pathMap the following url https://guide.freecodecamp.org/git/gui-options is mapped as follows.
"":{path: "/https:/", title: ""}
git:{path: "/https://guide.freecodecamp.org/git", title: "Git"}
gui-options:{path: "/https://guide.freecodecamp.org/git/gui-options", title: "Gui Options"}
guide.freecodecamp.org:{path: "/https://guide.freecodecamp.org", title: "Guide.freecodecamp.org"}
https::{path: "/https:", title: "Https:”}

My speculation is the url we are passing previously must have been relative but now its absolute. But I am not sure if this is the actual reason. Please correct me if wrong. @thomaskuntzz @Bouncey

**Comment by thomaskuntzz** [comment]
I'm not familiar with the code itself but looks like what you're saying makes sense...

**Comment by systimotic** [comment]
Good find @dhanushuUzumaki!

This changed when we switched to the npm package for the search (so we could reuse it on other freeCodeCamp projects) instead of having the code locally. When we did this, we also had an issue where links were `https://guide.freecodecamp.org/https://guide.freecodecamp.org/[category]/[article]` 😄

We didn't catch this in the PR because your branch did not have these new changes yet.
Changing this line: https://github.com/freeCodeCamp/guides/blob/a6bf63ea296875bea6bad399e2053c3799ed9c68/src/pageComponents/search/Results.jsx#L86 to
```js
{_index === 'guides' && <Breadcrumbs path={url.replace(isGuidesUrl, '')} />}
```
seemed to resolve the issue for me.

@dhanushuUzumaki Do you want to submit a PR for this?

**Comment by dhanushuUzumaki** [comment]
@systimotic Sure I would love to.
