### ISSUE TITLE
Javascript Arguments - possible content issue

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guides#8077]
The javascript arguments guide article (https://guide.freecodecamp.org/javascript/arguments) states that `The arguments object is an array-like object (meaning that it looks like an array but it’s not) that stores all of the arguments that you passed to a function and is proprietary to that function in particular. ` although I see a few possible problems with this.

* When running the function in repl.it's javascript interpreter I receive `{ 0: 'Mulder', 1: 'Scully', 2: 'Alex Kryceck' }` which looks like an object, although when stored in a variable I can access it just like an array so that part is correct. However you can do that with any object it's not specific to the arguments object.
<img width="631" alt="screen shot 2018-02-17 at 7 26 00 pm" src="https://user-images.githubusercontent.com/8227641/36346963-7495bc00-1418-11e8-9024-d5423b415c45.png">
* typeof states the data type is an object although this may be a custom data type, I'm not too familar with this.

So a few questions / suggestions:
* We should remove the statement saying the object looks like an array, it's just an object which may be customized.
* The specification (https://www.ecma-international.org/ecma-262/6.0/#sec-arguments-exotic-objects) states that in some cases the arguments will be an ordinary object and in some cases an arguments exotic object which has some additional properties explained in the specification.

What are your thoughts on this, how could we make things more clear to the users reading the guide?

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by johnkennedy9147** [comment]
I think it is correct to use "array-like". The arguments object is an array-like object in that the properties are accessed via an index rather than a property name. But it is not an array (which are special types of objects) and so the array methods are not available to use on it.  

The notation obj[0] is equivalent to obj["0"] but only where the object property name is a number (this may be an example of type coercion I'm not sure)

The article could do with clarification particularly on the point of how the arguments object is array like, it could probably be made a lot shorter.

**Comment by johnkennedy9147** [comment]
merged  PR #8079 - closing this issue
