### ISSUE TITLE
Elixir/Phoenix Nav Position

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guides#8081]
In the guide for Elixir, the Phoenix framework is a sub category of it, in JavaScript, React & Node are not sub categories of JavaScript, for consistency I think Phoenix should be a root category. Can I make these changes?

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by johnkennedy9147** [comment]
@nsuchy We are planning on making sub-categories within JavaScript for React etc but due to the large number of outstanding PRs the PR was blocked pending clearance of the backlog. I'll revisit the structure issue in JavaScript and resubmit my PR some time in the future.  

Having too many root categories makes for a bad UI.

**Comment by nsuchy** [comment]
Thank you for making me aware of that - so if I understand correctly we'll be grouping things like bootstrap with CSS, React & Angular under JS, etc?

**Comment by johnkennedy9147** [comment]
@nsuchy Exactly.  There is an issue regarding Navigation structure #414. I'll close this issue now.
